// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Ks1GD-Par5VTS6utSJf6fC5nCh8G4k8',
    appId: '1:895203889082:web:c15430f2f48a0cc4db1783',
    messagingSenderId: '895203889082',
    projectId: 'flutter-app-architecture-992e8',
    authDomain: 'flutter-app-architecture-992e8.firebaseapp.com',
    storageBucket: 'flutter-app-architecture-992e8.firebasestorage.app',
    measurementId: 'G-9FN3YKX8CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPjvUp2iAidtDC7Q3zSglpL_b4gHSCYN4',
    appId: '1:895203889082:android:b7c8cea6c4d90b7edb1783',
    messagingSenderId: '895203889082',
    projectId: 'flutter-app-architecture-992e8',
    storageBucket: 'flutter-app-architecture-992e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfdKM6FVPs0rMb3lLTs2I9jqXfWP5NDdc',
    appId: '1:895203889082:ios:5c77c4c9bbadf1f4db1783',
    messagingSenderId: '895203889082',
    projectId: 'flutter-app-architecture-992e8',
    storageBucket: 'flutter-app-architecture-992e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppArchitecture',
  );
}
